services:
  - type: web
    name: victor-backend
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: CLIENT_URL
        value: https://client-g2sa50oun-akhashcs24s-projects.vercel.app 